runtime: nodejs
env: flex
network:
  session_affinity: true
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 600
manual_scaling:
  instances: 1
