FROM node:14-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . ./

ENV NODE_ENV development
ENV REDIS_HOST redis
ENV REDIS_PORT 6379

CMD [ "npm", "run", "start:dev:docker" ]
